home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path('', views.home, name="main"),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

class Welcome_header(models.Model):
    special_name = models.CharField(max_length=30)
    welcome_message = models.CharField(max_length=50)
    education_center_name = models.CharField(max_length=30)
    description = models.TextField()
    image = models.ImageField(upload_to="header_image")


    def __str__(self):
        return self.special_name


class About(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()
    image = models.ImageField(upload_to="about_image")

    def __str__(self):
        return self.title


class Info_Teachers(models.Model):
    title = models.CharField(max_length=40)
    info = models.TextField()

    def __str__(self):
        return self.title

class Teachers(models.Model):
    image = models.ImageField(upload_to="teachers_image")
    name_of_teacher = models.CharField(max_length=35)

    def __str__(self):
        return self.name_of_teacher


class Vehicles_Facility(models.Model):
    title_name_of_vehicles = models.CharField(max_length=38)
    description = models.TextField()


    def __str__(self):
        return self.description[:10]


class Kind_of_vehicles(models.Model):
    image = models.ImageField(upload_to="vehicles_image")


class Student(models.Model):
    student_title = models.CharField(max_length=50)
    description = models.TextField()


    def __str__(self):
        return self.description[:10]


class Info_Student(models.Model):
    image = models.ImageField(upload_to="student_info_image")
    name = models.CharField(max_length=25)
    title = models.CharField(max_length=25)
    description = models.TextField()


    def __str__(self):
        return self.name
    

class Contact(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()


    def __str__(self):
        return self.title


class Message(models.Model):
    name = models.CharField(max_length=25)
    phone = models.CharField(max_length=12)
    email = models.EmailField()
    message = models.TextField()


    def __str__(self):
        return self.name


class Footer(models.Model):
    copy_right = models.CharField(max_length=100)
    tag_message = models.CharField(max_length=100)


    def __str__(self):
        return self.copy_right

home/views.py
from django.shortcuts import render
from . models import *

def home(request):
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        email = request.POST.get("email")
        message = request.POST.get("message")
        Message.objects.create(name=name, phone=phone, email=email, message=message)

    info_school = Welcome_header.objects.all().last()
    about = About.objects.all().last()
    info_teachers = Info_Teachers.objects.all().last()
    teachers = Teachers.objects.all()
    vehicles = Vehicles_Facility.objects.all().last()
    kind_ve = Kind_of_vehicles.objects.all()
    student = Student.objects.all().last()
    info_student = Info_Student.objects.all().last()
    contact = Contact.objects.all().last()
    footer = Footer.objects.all().last()

    return render(request, 'home/index.html', context={"info_school": info_school, 
    "about": about, "teachers": teachers,
    "info_teacher": info_teachers, "vehicles": vehicles,
    "kind_ve": kind_ve, "student": student,
    "info_student": info_student, "contact": contact,
    "footer": footer, })

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html>
  {% include "includes/head.html" %}
<body>
  <div class="top_container">
    <!-- header section strats -->
    {% include  'includes/header.html' %} 
  <!-- end header section -->
   
  <!-- about section -->
  {% include "includes/about.html" %}
  <!-- about section -->

  <!-- teacher section -->
  {% include "includes/teacher.html" %}
  <!-- teacher section -->
  
  <!-- vehicle section -->
  {% include "includes/vehicle.html" %}
  <!-- vehicle section -->

  <!-- client section -->
  {% include "includes/client.html" %}
  <!-- client section -->

  <!-- contact section -->
  {% include "includes/contact.html" %}
  <!-- end contact section -->

  <!-- admission section -->
  {% include "includes/admission.html" %}
  <!-- admission section -->


  <!-- landing section -->
  {% include "includes/landing.html" %}
  <!-- end landing section -->

  <!-- footer section -->
  {% include "includes/footer.html" %}
  <!-- footer section -->

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

  <script>
    // This example adds a marker to indicate the position of Bondi Beach in Sydney,
    // Australia.
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 11,
        center: {
          lat: 40.645037,
          lng: -73.880224
        },
      });

      var image = 'images/maps-and-flags.png';
      var beachMarker = new google.maps.Marker({
        position: {
          lat: 40.645037,
          lng: -73.880224
        },
        map: map,
        icon: image
      });
    }
  </script>
  <!-- google map js -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap">
  </script>
  <!-- end google map js -->
</body>

</html>

templates/includes/about.html
{% load static %}

<section class="about_section layout_padding">
    <div class="container">
      <h2 class="main-heading ">
        {{ about.title }}
      </h2>
      <p class="text-center">
        {{ about.description }}
      </p>
      <div class="about_img-box ">
        <img src="{{ about.image.url }}" alt="" class="img-fluid w-100">
      </div>
      <div class="d-flex justify-content-center mt-5">
        <a href="{% url 'home:main' %}" class="call_to-btn  ">

          <span>
            Read More
          </span>
          <img src="{% static 'images/right-arrow.png' %}" alt="">
        </a>
      </div>
    </div>
  </section>

templates/includes/admission.html
{% load static %}

{% comment %} <section class="admission_section ">
    <div class="container-fluid position-relative">
      <div class="row h-100">
        <div id="map" class="h-100 w-100 ">
        </div>
        <div class="container">
          <div class="admission_container position-absolute">
            <div class="admission_img-box">
              <img src="{% static 'images/kidss.jpg' %}" alt="">
            </div>
            <div class="admission_detail">
              <h3>
                Apply for Admission
              </h3>
              <p class="mt-3 mb-4">
                There are many variations of passages of Lorem Ipsum available, but the majority h
              </p>
              <div class="">
                <a href="" class="admission_btn btn_on-hover">
                  Read More
                </a>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section> {% endcomment %}

templates/includes/client.html
{% load static %}

<section class="client_section layout_padding">
    <div class="container">
      <h2 class="main-heading ">
        {{ student.student_title }}
      </h2>
      <p class="text-center">
        {{ student.description }}
      </p>
      <div class="layout_padding2">
        <div class="client_container d-flex flex-column">
          <div class="client_detail d-flex align-items-center">
            <div class="client_img-box ">
              <img src="{{ info_student.image.url }}" alt="">
            </div>
            <div class="client_detail-box">
              <h4>
                {{ info_student.name }}
              </h4>
              <span>
                {{ info_student.title }}
              </span>
            </div>
          </div>
          <div class="client_text mt-4">
            <p>
              {{ info_student.description }}

            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/includes/contact.html
{% load static %}

<section class="contact_section layout_padding-bottom">
    <div class="container">

      <h2 class="main-heading">
        {{ contact.title }}

      </h2>
      <p class="text-center">
        {{ contact.description }}

      </p>
      <div class="">
        <div class="contact_section-container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="contact-form">
                <form method="post">
                {% csrf_token %}
                  <div>
                    <input type="text" name="name" placeholder="Name">
                  </div>
                  <div>
                    <input type="text" name="phone" placeholder="Phone Number">
                  </div>
                  <div>
                    <input type="email" name="email" placeholder="Email">
                  </div>
                  <div>
                    <input type="text" name="message" placeholder="Message" class="input_message">
                  </div>
                  <div class="d-flex justify-content-center">
                    <button type="submit" class="btn_on-hover">
                      Send Message 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>

templates/includes/footer.html
{% load static %}

<section class="container-fluid footer_section">
    <p>
      Copyright &copy; {{ footer.copy_right }}
      <a href="https://django.com">{{ footer.tag_message }}</a>
    </p>
  </section>

templates/includes/head.html
{% load static %}

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
  
    <title>Adward</title>
  
  
  
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <!-- progress barstle -->
    {% comment %} <link rel="stylesheet" href="{% static 'css/css-circular-prog-bar.css' %}"> {% endcomment %}
    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <!-- font wesome stylesheet -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  
  
  
  
    {% comment %} <link rel="stylesheet" href="{% static 'css/css-circular-prog-bar.css' %}"> {% endcomment %}
  
  
  </head>
  

templates/includes/header.html
{% load static %}

<header class="header_section">
    <div class="container">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="{% url 'home:main' %}">
          <img src="{% static 'images/logo.png' %}" alt="">
          <span>
            {{ info_school.special_name }}
          </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
            <ul class="navbar-nav  ">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:main' %}"> Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'home:main' %}"> About </a>
              </li>

              <li class="nav-item ">
                <a class="nav-link" href="{% url 'home:main' %}"> Teacher </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:main' %}"> vehicle </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:main' %}">Contact Us</a>
              </li>

            </ul>
            {% comment %} <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
              <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
            </form> {% endcomment %}
          </div>
      </nav>
    </div>
  </header>
  <section class="hero_section ">
    <div class="hero-container container">
      <div class="hero_detail-box">
        <h3>
          {{ info_school.welcome_message }}
        </h3>
        <h1>
          {{ info_school.education_center_name }}
        </h1>
        <p>
          {{ info_school.description }}
        </p>
        <div class="hero_btn-continer">
          <a href="" class="call_to-btn btn_white-border">
            <span>
              Contact
            </span>
            <img src="{% static 'images/right-arrow.png' %}" alt="">
          </a>
        </div>
      </div>
      <div class="hero_img-container">
        <div>
          <img src="{{ info_school.image.url }}" alt=""
           style="width: 630px; height: 470px; margin-right: auto; margin-left: 29px; margin-top: 0px; " 
           class="img-fluid">
        </div>
      </div>
    </div>
  </section>
</div>

templates/includes/landing.html
{% load static %}

{% comment %} <section class="landing_section layout_padding">
    <div class="container">
      <h2 class="main-heading">
        Free Multipurpose Responsive

      </h2>
      <h2 class="main-heading number_heading">
        Landing Page 2019

      </h2>
      <p class="landing_detail text-center">
        There are many variations of passages of Lorem Ipsum available, but the majority There are many variations of
        passages of Lorem Ipsum available, but the majority h
        
      </p>
    </div>
  </section> {% endcomment %}

templates/includes/teacher.html
{% load static %}

<section class="teacher_section layout_padding-bottom">
    <div class="container">
      <h2 class="main-heading ">
        {{ info_teacher.title }}
      </h2>
      <p class="text-center">
        {{ info_teacher.info }}
      </p>
      <div class="teacher_container layout_padding2">
        <div class="card-deck">
          {% for object in teachers %}
          <div class="card">
            <img class="card-img-top" src="{{ object.image.url }}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">{{ object.name_of_teacher }}</h5>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>


      <div class="d-flex justify-content-center mt-3">
        <a href="{% url 'home:main' %}" class="call_to-btn  ">

          <span>
            See More
          </span>
          <img src="{% static 'images/right-arrow.png' %}" alt="">
        </a>
      </div>
    </div>
  </section>

templates/includes/vehicle.html
{% load static %}

<section class="vehicle_section layout_padding">
    <div class="container">
      <h2 class="main-heading ">
        {{ vehicles.title_name_of_vehicles }}
      </h2>
      <p class="text-center">
        {{ vehicles.description }}
      </p>
      <div class="layout_padding-top">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              {% for machin in kind_ve %}
            </div>
            <div class="carousel-item">
              <div class="vehicle_img-box ">
                <img src="{{ machin.image.url }}" alt="" class="img-fluid w-100">
              </div>
              {% endfor %}
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

    </div>
  </section>